<?php
  class dbSettingsConfigHandler {

    public function initialize() {
    }

    public function execute($configFiles) {  
      $databaseManager = new sfDatabaseManager();
      $databaseManager->initialize();

      $retval = "<?php\n".
                "// auto-generated by ".__CLASS__."\n".
                "// date: ".date('Y/m/d H:i:s')."\n";

      $settings = sfSettingPeer::doSelect(new Criteria());
      if ($settings) foreach($settings as $p) 
        if (($p->getEnv() == SF_ENVIRONMENT or $p->getEnv() == 'all') and 
             $p->getName())
          $retval .= "DEFINE('".strtoupper($p->getName()).
                     "','".htmlentities($p->getValue())."');\n";      
      $retval .= "?>\n";
      
      return $retval;
    }
  }
?>