<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/02/10 14:36:20
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 'member',
  ),
);
