rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
myCultureFilter:
   class: myCultureFilter

security_filter:
   class: sfGuardBasicSecurityFilter

cache:     ~
common:    ~

flash:     ~
execution: ~
