<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/02/10 14:21:21

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:dbname=ARANOVA_aranet;host=localhost',
  'username' => 'aranet',
  'password' => 'cKKZ2ATbcAJa2d4K',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'classname' => 'PropelPDO',
  'name' => 'propel',
)),);
