<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/02/10 14:21:21
return array(
'sf_guard_signin' => new sfRoute('/login', array (
  'module' => 'sfGuardAuth',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_signout' => new sfRoute('/logout', array (
  'module' => 'sfGuardAuth',
  'action' => 'signout',
), array (
), array (
)),
'sf_guard_password' => new sfRoute('/request_password', array (
  'module' => 'sfGuardAuth',
  'action' => 'password',
), array (
), array (
)),
'sf_guard_profile' => new sfRoute('/profile', array (
  'module' => 'sfGuardUser',
  'action' => 'show',
), array (
), array (
)),
'sf_guard_restringed' => new sfRoute('/restringed', array (
  'module' => 'sfGuardAuth',
  'action' => 'restringed',
), array (
), array (
)),
'show_graphic' => new sfRoute('/dasboard/showGraphic', array (
  'module' => 'dashboard',
  'action' => 'showGraphic',
), array (
), array (
)),
'copyright' => new sfRoute('/copyright', array (
  'module' => 'static',
  'action' => 'index',
  'content' => 'copyright',
), array (
), array (
)),
'contact_show_by_id' => new sfRoute('/contact/show/:id', array (
  'module' => 'contact',
  'action' => 'show',
), array (
), array (
)),
'contact_edit_by_id' => new sfRoute('/contact/edit/:id', array (
  'module' => 'contact',
  'action' => 'edit',
), array (
), array (
)),
'contact_delete_by_id' => new sfRoute('/contact/delete/:id', array (
  'module' => 'contact',
  'action' => 'delete',
), array (
), array (
)),
'contact_list_by_tag' => new sfRoute('/contact/list/:tag', array (
  'module' => 'contact',
  'action' => 'listByTag',
), array (
), array (
)),
'contact_list' => new sfRoute('/contact/list', array (
  'module' => 'contact',
  'action' => 'list',
), array (
), array (
)),
'contact_list_remove_filters' => new sfRoute('/contact/list?contact_filters[]=', array (
  'module' => 'contact',
  'action' => 'list',
), array (
), array (
)),
'contact_index' => new sfRoute('/contact', array (
  'module' => 'contact',
  'action' => 'list',
), array (
), array (
)),
'contact_create' => new sfRoute('/contact/create', array (
  'module' => 'contact',
  'action' => 'create',
), array (
), array (
)),
'contact_delete_all' => new sfRoute('/contact/delete', array (
  'module' => 'contact',
  'action' => 'delete',
), array (
), array (
)),
'client_stats_by_id' => new sfRoute('/client/stats/:id', array (
  'module' => 'client',
  'action' => 'stats',
), array (
), array (
)),
'client_show_by_id' => new sfRoute('/client/show/:id', array (
  'module' => 'client',
  'action' => 'show',
), array (
), array (
)),
'client_show_deleted_by_id' => new sfRoute('/client/show/:id/deleted', array (
  'module' => 'client',
  'action' => 'show',
  'deleted' => true,
), array (
), array (
)),
'client_edit_by_id' => new sfRoute('/client/edit/:id', array (
  'module' => 'client',
  'action' => 'edit',
), array (
), array (
)),
'client_delete_by_id' => new sfRoute('/client/delete/:id', array (
  'module' => 'client',
  'action' => 'delete',
), array (
), array (
)),
'client_list_by_tag' => new sfRoute('/client/list/:tag', array (
  'module' => 'client',
  'action' => 'listByTag',
), array (
), array (
)),
'client_list' => new sfRoute('/client/list', array (
  'module' => 'client',
  'action' => 'list',
), array (
), array (
)),
'client_list_remove_filters' => new sfRoute('/client/list?client_filters[]=', array (
  'module' => 'client',
  'action' => 'list',
), array (
), array (
)),
'client_index' => new sfRoute('/client', array (
  'module' => 'client',
  'action' => 'list',
), array (
), array (
)),
'client_create' => new sfRoute('/client/create', array (
  'module' => 'client',
  'action' => 'create',
), array (
), array (
)),
'client_delete_all' => new sfRoute('/client/delete', array (
  'module' => 'client',
  'action' => 'delete',
), array (
), array (
)),
'project_create' => new sfRoute('/project/create', array (
  'module' => 'project',
  'action' => 'create',
), array (
), array (
)),
'project_show_by_id' => new sfRoute('/project/show/:id', array (
  'module' => 'project',
  'action' => 'show',
), array (
), array (
)),
'project_edit_by_id' => new sfRoute('/project/edit/:id', array (
  'module' => 'project',
  'action' => 'edit',
), array (
), array (
)),
'project_index' => new sfRoute('/project', array (
  'module' => 'project',
  'action' => 'list',
), array (
), array (
)),
'project_list' => new sfRoute('/project/list', array (
  'module' => 'project',
  'action' => 'list',
), array (
), array (
)),
'project_list_remove_filters' => new sfRoute('/project/list?project_filters[]=', array (
  'module' => 'project',
  'action' => 'list',
), array (
), array (
)),
'project_delete_all' => new sfRoute('/project/delete', array (
  'module' => 'project',
  'action' => 'delete',
), array (
), array (
)),
'project_create_from_object' => new sfRoute('/project/create/related/:related/:id', array (
  'module' => 'project',
  'action' => 'create',
), array (
), array (
)),
'budget_create_from_object' => new sfRoute('/budget/create/related/:related/id/:id', array (
  'module' => 'budget',
  'action' => 'create',
), array (
), array (
)),
'budget_stats_by_id' => new sfRoute('/budget/stats/:id', array (
  'module' => 'budget',
  'action' => 'stats',
), array (
), array (
)),
'budget_show_by_id' => new sfRoute('/budget/show/:id', array (
  'module' => 'budget',
  'action' => 'show',
), array (
), array (
)),
'budget_edit_by_id' => new sfRoute('/budget/edit/:id', array (
  'module' => 'budget',
  'action' => 'edit',
), array (
), array (
)),
'budget_delete_by_id' => new sfRoute('/budget/delete/:id', array (
  'module' => 'budget',
  'action' => 'delete',
), array (
), array (
)),
'budget_list_by_tag' => new sfRoute('/budget/list/:tag', array (
  'module' => 'budget',
  'action' => 'listByTag',
), array (
), array (
)),
'budget_list' => new sfRoute('/budget/list', array (
  'module' => 'budget',
  'action' => 'list',
), array (
), array (
)),
'budget_minilist' => new sfRoute('/budget/minilist/related/:related/id/:id', array (
  'module' => 'budget',
  'action' => 'minilist',
), array (
), array (
)),
'budget_list_remove_filters' => new sfRoute('/budget/list?budget_filters[]=', array (
  'module' => 'budget',
  'action' => 'list',
), array (
), array (
)),
'budget_index' => new sfRoute('/budget', array (
  'module' => 'budget',
  'action' => 'list',
), array (
), array (
)),
'budget_create' => new sfRoute('/budget/create', array (
  'module' => 'budget',
  'action' => 'create',
), array (
), array (
)),
'budget_delete_all' => new sfRoute('/budget/delete', array (
  'module' => 'budget',
  'action' => 'delete',
), array (
), array (
)),
'timesheet_stats_by_id' => new sfRoute('/timesheet/stats/:id', array (
  'module' => 'timesheet',
  'action' => 'stats',
), array (
), array (
)),
'timesheet_show_by_id' => new sfRoute('/timesheet/show/:id', array (
  'module' => 'timesheet',
  'action' => 'show',
), array (
), array (
)),
'timesheet_edit_by_id' => new sfRoute('/timesheet/edit/:id', array (
  'module' => 'timesheet',
  'action' => 'edit',
), array (
), array (
)),
'timesheet_delete_by_id' => new sfRoute('/timesheet/delete/:id', array (
  'module' => 'timesheet',
  'action' => 'delete',
), array (
), array (
)),
'timesheet_list_by_tag' => new sfRoute('/timesheet/list/:tag', array (
  'module' => 'timesheet',
  'action' => 'listByTag',
), array (
), array (
)),
'timesheet_list' => new sfRoute('/timesheet/list', array (
  'module' => 'timesheet',
  'action' => 'list',
), array (
), array (
)),
'timesheet_list_remove_filters' => new sfRoute('/timesheet/list?timesheet_filters[]=', array (
  'module' => 'timesheet',
  'action' => 'list',
), array (
), array (
)),
'timesheet_index' => new sfRoute('/timesheet', array (
  'module' => 'timesheet',
  'action' => 'list',
), array (
), array (
)),
'timesheet_create' => new sfRoute('/timesheet/create', array (
  'module' => 'timesheet',
  'action' => 'create',
), array (
), array (
)),
'timesheet_delete_all' => new sfRoute('/timesheet/delete', array (
  'module' => 'timesheet',
  'action' => 'delete',
), array (
), array (
)),
'timesheet_reports' => new sfRoute('/timesheet/reports', array (
  'module' => 'timesheet',
  'action' => 'reports',
), array (
), array (
)),
'invoice_create_from_object' => new sfRoute('/invoice/create/related/:related/:id', array (
  'module' => 'invoice',
  'action' => 'create',
), array (
), array (
)),
'invoice_stats_by_id' => new sfRoute('/invoice/stats/:id', array (
  'module' => 'invoice',
  'action' => 'stats',
), array (
), array (
)),
'invoice_show_by_id' => new sfRoute('/invoice/show/:id', array (
  'module' => 'invoice',
  'action' => 'show',
), array (
), array (
)),
'invoice_edit_by_id' => new sfRoute('/invoice/edit/:id', array (
  'module' => 'invoice',
  'action' => 'edit',
), array (
), array (
)),
'invoice_delete_by_id' => new sfRoute('/invoice/delete/:id', array (
  'module' => 'invoice',
  'action' => 'delete',
), array (
), array (
)),
'invoice_list_by_tag' => new sfRoute('/invoice/list/:tag', array (
  'module' => 'invoice',
  'action' => 'listByTag',
), array (
), array (
)),
'invoice_list' => new sfRoute('/invoice/list', array (
  'module' => 'invoice',
  'action' => 'list',
), array (
), array (
)),
'invoice_list_remove_filters' => new sfRoute('/invoice/list?invoice_filters[]=', array (
  'module' => 'invoice',
  'action' => 'list',
), array (
), array (
)),
'invoice_index' => new sfRoute('/invoice', array (
  'module' => 'invoice',
  'action' => 'list',
), array (
), array (
)),
'invoice_create' => new sfRoute('/invoice/create', array (
  'module' => 'invoice',
  'action' => 'create',
), array (
), array (
)),
'invoice_delete_all' => new sfRoute('/invoice/delete', array (
  'module' => 'invoice',
  'action' => 'delete',
), array (
), array (
)),
'invoice_reports' => new sfRoute('/invoice/reports', array (
  'module' => 'invoice',
  'action' => 'reports',
), array (
), array (
)),
'cash_stats_by_id' => new sfRoute('/cash/stats/:id', array (
  'module' => 'cash',
  'action' => 'stats',
), array (
), array (
)),
'cash_show_by_id' => new sfRoute('/cash/show/:id', array (
  'module' => 'cash',
  'action' => 'show',
), array (
), array (
)),
'cash_edit_by_id' => new sfRoute('/cash/edit/:id', array (
  'module' => 'cash',
  'action' => 'edit',
), array (
), array (
)),
'cash_delete_by_id' => new sfRoute('/cash/delete/:id', array (
  'module' => 'cash',
  'action' => 'delete',
), array (
), array (
)),
'cash_list_by_tag' => new sfRoute('/cash/list/:tag', array (
  'module' => 'cash',
  'action' => 'listByTag',
), array (
), array (
)),
'cash_list' => new sfRoute('/cash/list', array (
  'module' => 'cash',
  'action' => 'list',
), array (
), array (
)),
'cash_list_remove_filters' => new sfRoute('/cash/list?cash_filters[]=', array (
  'module' => 'cash',
  'action' => 'list',
), array (
), array (
)),
'cash_index' => new sfRoute('/cash', array (
  'module' => 'cash',
  'action' => 'list',
), array (
), array (
)),
'cash_create' => new sfRoute('/cash/create', array (
  'module' => 'cash',
  'action' => 'create',
), array (
), array (
)),
'cash_delete_all' => new sfRoute('/cash/delete', array (
  'module' => 'cash',
  'action' => 'delete',
), array (
), array (
)),
'cash_reports' => new sfRoute('/cash/reports', array (
  'module' => 'cash',
  'action' => 'reports',
), array (
), array (
)),
'member_list' => new sfRoute('/member/list', array (
  'module' => 'member',
  'action' => 'list',
), array (
), array (
)),
'member_list_remove_filters' => new sfRoute('/member/list?member_filters[]=', array (
  'module' => 'member',
  'action' => 'list',
), array (
), array (
)),
'member_index' => new sfRoute('/member', array (
  'module' => 'member',
  'action' => 'list',
), array (
), array (
)),
'member_create' => new sfRoute('/member/create', array (
  'module' => 'member',
  'action' => 'create',
), array (
), array (
)),
'file_list' => new sfRoute('/file/list', array (
  'module' => 'file',
  'action' => 'list',
), array (
), array (
)),
'file_list_remove_filters' => new sfRoute('/file/list?file_filters[]=', array (
  'module' => 'file',
  'action' => 'list',
), array (
), array (
)),
'file_index' => new sfRoute('/file', array (
  'module' => 'file',
  'action' => 'list',
), array (
), array (
)),
'file_create' => new sfRoute('/file/create', array (
  'module' => 'file',
  'action' => 'create',
), array (
), array (
)),
'expense_stats_by_id' => new sfRoute('/expense/stats/:id', array (
  'module' => 'expense',
  'action' => 'stats',
), array (
), array (
)),
'expense_show_by_id' => new sfRoute('/expense/show/:id', array (
  'module' => 'expense',
  'action' => 'show',
), array (
), array (
)),
'expense_edit_by_id' => new sfRoute('/expense/edit/:id', array (
  'module' => 'expense',
  'action' => 'edit',
), array (
), array (
)),
'expense_delete_by_id' => new sfRoute('/expense/delete/:id', array (
  'module' => 'expense',
  'action' => 'delete',
), array (
), array (
)),
'expense_list_by_tag' => new sfRoute('/expense/list/:tag', array (
  'module' => 'expense',
  'action' => 'listByTag',
), array (
), array (
)),
'expense_list' => new sfRoute('/expense/list', array (
  'module' => 'expense',
  'action' => 'list',
), array (
), array (
)),
'expense_list_remove_filters' => new sfRoute('/expense/list?expense_filters[]=', array (
  'module' => 'expense',
  'action' => 'list',
), array (
), array (
)),
'expense_index' => new sfRoute('/expense', array (
  'module' => 'expense',
  'action' => 'list',
), array (
), array (
)),
'expense_create' => new sfRoute('/expense/create', array (
  'module' => 'expense',
  'action' => 'create',
), array (
), array (
)),
'expense_delete_all' => new sfRoute('/expense/delete', array (
  'module' => 'expense',
  'action' => 'delete',
), array (
), array (
)),
'expense_reports' => new sfRoute('/expense/reports', array (
  'module' => 'expense',
  'action' => 'reports',
), array (
), array (
)),
'income_stats_by_id' => new sfRoute('/income/stats/:id', array (
  'module' => 'income',
  'action' => 'stats',
), array (
), array (
)),
'income_show_by_id' => new sfRoute('/income/show/:id', array (
  'module' => 'income',
  'action' => 'show',
), array (
), array (
)),
'income_edit_by_id' => new sfRoute('/income/edit/:id', array (
  'module' => 'income',
  'action' => 'edit',
), array (
), array (
)),
'income_delete_by_id' => new sfRoute('/income/delete/:id', array (
  'module' => 'income',
  'action' => 'delete',
), array (
), array (
)),
'income_list_by_tag' => new sfRoute('/income/list/:tag', array (
  'module' => 'income',
  'action' => 'listByTag',
), array (
), array (
)),
'income_list' => new sfRoute('/income/list', array (
  'module' => 'income',
  'action' => 'list',
), array (
), array (
)),
'income_list_remove_filters' => new sfRoute('/income/list?income_filters[]=', array (
  'module' => 'income',
  'action' => 'list',
), array (
), array (
)),
'income_index' => new sfRoute('/income', array (
  'module' => 'income',
  'action' => 'list',
), array (
), array (
)),
'income_create' => new sfRoute('/income/create', array (
  'module' => 'income',
  'action' => 'create',
), array (
), array (
)),
'income_delete_all' => new sfRoute('/income/delete', array (
  'module' => 'income',
  'action' => 'delete',
), array (
), array (
)),
'income_reports' => new sfRoute('/income/reports', array (
  'module' => 'income',
  'action' => 'reports',
), array (
), array (
)),
'income_create_from_object' => new sfRoute('/income/create/related/:related/:id', array (
  'module' => 'income',
  'action' => 'create',
), array (
), array (
)),
'vendor_stats_by_id' => new sfRoute('/vendor/stats/:id', array (
  'module' => 'vendor',
  'action' => 'stats',
), array (
), array (
)),
'vendor_show_by_id' => new sfRoute('/vendor/show/:id', array (
  'module' => 'vendor',
  'action' => 'show',
), array (
), array (
)),
'vendor_edit_by_id' => new sfRoute('/vendor/edit/:id', array (
  'module' => 'vendor',
  'action' => 'edit',
), array (
), array (
)),
'vendor_delete_by_id' => new sfRoute('/vendor/delete/:id', array (
  'module' => 'vendor',
  'action' => 'delete',
), array (
), array (
)),
'vendor_list_by_tag' => new sfRoute('/vendor/list/:tag', array (
  'module' => 'vendor',
  'action' => 'listByTag',
), array (
), array (
)),
'vendor_list' => new sfRoute('/vendor/list', array (
  'module' => 'vendor',
  'action' => 'list',
), array (
), array (
)),
'vendor_list_remove_filters' => new sfRoute('/vendor/list?vendor_filters[]=', array (
  'module' => 'vendor',
  'action' => 'list',
), array (
), array (
)),
'vendor_index' => new sfRoute('/vendor', array (
  'module' => 'vendor',
  'action' => 'list',
), array (
), array (
)),
'vendor_create' => new sfRoute('/vendor/create', array (
  'module' => 'vendor',
  'action' => 'create',
), array (
), array (
)),
'vendor_delete_all' => new sfRoute('/vendor/delete', array (
  'module' => 'vendor',
  'action' => 'delete',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'dashboard',
  'action' => 'index',
), array (
), array (
)),
'default_symfony' => new sfRoute('/symfony/:action/*', array (
  'module' => 'default',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
