default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [aranet]

  javascripts:    [functions]

  has_layout:     on
  layout:         layout

minilistSuccess:
  has_layout: off