default:
  http_metas:
    content-type: "text/html; charset=utf-8"

  metas:
    title:        "<?php echo TITLE ?>"
    generator:    "<?php echo TITLE . ' (' . VERSION . ')' ?>"
    robots:       no-index, no-follow
    description:  "<?php echo DESCRIPTION ?>"
    keywords:     ARANOVA, aranet
    language:     es

  stylesheets:    [ base.min.css, ThemeBlue/theme.min.css, aranet.min.css ]

  javascripts:    [ jscook/JSCookMenu.min.js, jscook/ThemeBlue/theme.min.js, functions.min.js ]

  has_layout:     on
  layout:         layout

  slots:

  use_default_slots: 0

  components: 
    widget_subnav: [widgets, subnav]
    widget_calendar: [widgets, calendar]
    widget_tags: [widgets, tags]

autocompleteSuccess:
  has_layout:   off
