all:
  company:
    name:         ARANOVA
    logo:         aranova/aranova_logo.gif
    site:         http://www.aranova.es

  version:        "1.2.0"
  tmp_path:       /tmp/
  app:
    title:        "ARANet Backoffice Web Management"
    icon:         aranova.ico
    url:          http://anet.aranova-it.com
    description:  "Aplicación web de gestión, control y organización de ARANOVA"

  mail:
    smtp_host:
    smtp_user:
    smtp_password:
    from:
    sender:
    reply_to:

  margin_model:     sales
  invoice:
    number_format:  %04s
    first_number:   1

      