{"recordsReturned":20,
    "totalRecords":2,
    "startIndex":1,
    "sort":"id",
    "dir":"asc",
    "records":[
        {"id":"6",
        "name":"Sr. Pablo Sánchez Gálvez",
        "birthday":"1977-09-08",
        "phone":"+34 976 517 611",
        "fax":"+34 976 517 611",
        "mobile":"+34 627 52 56 60",
        "email":"pablo.sanchez@aranova.es"},
        {"id":"7",
        "name":"Otro Mas",
        "birthday":"",
        "phone":"",
        "fax":"",
        "mobile":"",
        "email":""},
    ]
}