all:
  sf_guard_plugin: 
    profile_class: sfGuardUserProfile
    field_name: user_id
    needs_mail_activation: true
    success_signout_url: @homepage

  fop:
    path:  <?php echo sfConfig::get('sf_data_dir') ?>/fop-0.94/fop
    conf_file: <?php echo sfConfig::get('sf_data_dir') ?>/fop-0.94/conf/fop.xconf
