rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
myCultureFilter:
   class: myCultureFilter

security_filter:
   class: sfGuardBasicSecurityFilter

cache:     ~
common:    ~

sfCombineFilter:
  class:   sfCombineFilter
  param:
    javascripts:    false
    stylesheets:    false
    root_js_only:   false
    root_css_only:  false

flash:     ~
execution: ~
