default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [aranet]

  javascripts:    [functions, /static/ysf/yui/calendar/calendar.js, /static/ysf/yui/yahoo-dom-event/yahoo-dom-event.js, /static/ysf/yui/animation/animation.js, /static/ysf/yui/container/container_core.js, /static/ysf/yui/menu/menu.js]

  has_layout:     on
  layout:         layout

minilistSuccess:
  has_layout: off