<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/02/10 14:04:10
sfConfig::add(array(
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_field_name' => 'user_id',
  'app_sf_guard_plugin_needs_mail_activation' => true,
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
  'app_fop_path' => '/Users/pablo/Sites/ARANOVA/Google/ARANet/branches/aranet_12/data/fop-0.94/fop',
  'app_fop_conf_file' => 'conf/fop.xconf',
));
