<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/02/10 14:36:20
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
