<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/02/10 14:21:20
sfConfig::add(array(
  'aranet_company_name' => 'ARANOVA',
  'aranet_company_logo' => 'aranova/aranova_logo.gif',
  'aranet_company_site' => 'http://www.aranova.es',
  'aranet_version' => '1.2.0',
  'aranet_tmp_path' => '/tmp/',
  'aranet_app_title' => 'ARANet Backoffice Web Management',
  'aranet_app_icon' => 'aranova.ico',
  'aranet_app_url' => 'http://anet.aranova-it.com',
  'aranet_app_description' => 'Aplicación web de gestión, control y organización de ARANOVA',
  'aranet_mail_smtp_host' => NULL,
  'aranet_mail_smtp_user' => NULL,
  'aranet_mail_smtp_password' => NULL,
  'aranet_mail_from' => NULL,
  'aranet_mail_sender' => NULL,
  'aranet_mail_reply_to' => NULL,
  'aranet_margin_model' => 'sales',
  'aranet_invoice_number_format' => '%04s',
  'aranet_invoice_first_number' => 1,
));
