<?php
// auto-generated by sfCacheConfigHandler
// date: 2009/02/10 14:21:22
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

