<?php
// auto-generated by sfViewConfigHandler
// date: 2009/02/10 14:21:22
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'minilistSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'minilistSuccess')
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'ARANet Backoffice Web Management', false, false);
  $response->addMeta('generator', 'ARANet ()', false, false);
  $response->addMeta('robots', 'no-index, no-follow', false, false);
  $response->addMeta('description', 'Aplicación web de gestión, control y organización de ARANOVA', false, false);
  $response->addMeta('keywords', 'ARANOVA, aranet', false, false);
  $response->addMeta('language', 'es', false, false);

  $response->addStylesheet('base-min', '', array ());
  $response->addStylesheet('reset-fonts-grids', '', array ());
  $response->addStylesheet('aranet', '', array ());
  $response->addStylesheet('ThemeBlue/theme.min.css', '', array ());
  $response->addJavascript('jscook/JSCookMenu.min.js', '', array ());
  $response->addJavascript('jscook/ThemeBlue/theme.min.js', '', array ());
  $response->addJavascript('functions', '', array ());
  $response->addJavascript('jquery-1.3.1.min', '', array ());
  $response->addJavascript('jquery.datePicker.min-2.1.2', '', array ());
}
else
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'ARANet Backoffice Web Management', false, false);
  $response->addMeta('generator', 'ARANet ()', false, false);
  $response->addMeta('robots', 'no-index, no-follow', false, false);
  $response->addMeta('description', 'Aplicación web de gestión, control y organización de ARANOVA', false, false);
  $response->addMeta('keywords', 'ARANOVA, aranet', false, false);
  $response->addMeta('language', 'es', false, false);

  $response->addStylesheet('base-min', '', array ());
  $response->addStylesheet('reset-fonts-grids', '', array ());
  $response->addStylesheet('aranet', '', array ());
  $response->addStylesheet('ThemeBlue/theme.min.css', '', array ());
  $response->addJavascript('jscook/JSCookMenu.min.js', '', array ());
  $response->addJavascript('jscook/ThemeBlue/theme.min.js', '', array ());
  $response->addJavascript('functions', '', array ());
  $response->addJavascript('jquery-1.3.1.min', '', array ());
  $response->addJavascript('jquery.datePicker.min-2.1.2', '', array ());
}

